Theme dark
Katya-Kondratchuk/So-Yummy pull request #148
Opened 2023-03-16 22:18 UTC by JC4114

2023-03-16 22:21 UTC, Katya-Kondratchuk requested changes

2023-03-16 22:21 UTC, Katya-Kondratchuk commented on src/index.css
> +  transition: 1s;
переменные пишутся перез два тире и мы не вносим изменения в общих файлах таких как этот

2023-03-17 08:37 UTC, JC4114 commented on src/index.css
> +  transition: 1s;
fix

2023-03-17 11:11 UTC, Katya-Kondratchuk approved these changes

2023-03-17 11:11 UTC, merged